//
// Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
//
// On Tue Jul 29 14:28:07 +04 2025
//
//
// Ports:
// Name                         I/O  size props
// fn_decode                      O    75
// fn_decode_inst                 I    32
// fn_decode_csrs                 I   242
// fn_decode_compressed           I     1
// fn_decode_debug                I     5
//
// Combinational paths from inputs to outputs:
//   (fn_decode_inst,
//    fn_decode_csrs,
//    fn_decode_compressed,
//    fn_decode_debug) -> fn_decode
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_decode(fn_decode_inst,
			fn_decode_csrs,
			fn_decode_compressed,
			fn_decode_debug,
			fn_decode);
  // value method fn_decode
  input  [31 : 0] fn_decode_inst;
  input  [241 : 0] fn_decode_csrs;
  input  fn_decode_compressed;
  input  [4 : 0] fn_decode_debug;
  output [74 : 0] fn_decode;

  // signals for module outputs
  wire [74 : 0] fn_decode;

  // remaining internal signals
  wire [31 : 0] immediate_value__h32;
  wire [6 : 0] instr_meta_funct_cause__h120, temp1___1__h197, temp1__h38;
  wire [4 : 0] x__h103, x__h48, x__h49, x__h50;
  wire [3 : 0] fn__h36, fn_decode_insttype___d12;
  wire [2 : 0] fn_decode_mem_access___d13, fn_decode_rs2type___d10;
  wire [1 : 0] fn_decode_rs1type___d9;
  wire fn_decode_rdtype___d8, fn_decode_rs3type___d7;

  // value method fn_decode
  assign fn_decode =
	     { 1'd0,
	       x__h48,
	       x__h49,
	       x__h50,
	       x__h103,
	       fn_decode_rs3type___d7,
	       fn_decode_rdtype___d8,
	       fn_decode_rs1type___d9,
	       fn_decode_rs2type___d10,
	       fn_decode_insttype___d12,
	       fn_decode_mem_access___d13,
	       immediate_value__h32,
	       instr_meta_funct_cause__h120,
	       fn_decode_mem_access___d13 == 3'd3 ||
	       fn_decode_mem_access___d13 == 3'd4 ||
	       fn_decode_insttype___d12 == 4'd5 ||
	       fn_decode_mem_access___d13 == 3'd5 } ;

  // remaining internal signals
  module_fn_decode_immediate instance_fn_decode_immediate_12(.fn_decode_immediate_inst(fn_decode_inst),
							     .fn_decode_immediate_csrs(fn_decode_csrs),
							     .fn_decode_immediate(immediate_value__h32));
  module_fn_decode_fn instance_fn_decode_fn_6(.fn_decode_fn_inst(fn_decode_inst),
					      .fn_decode_fn_csrs(fn_decode_csrs),
					      .fn_decode_fn(fn__h36));
  module_fn_decode_rs3 instance_fn_decode_rs3_10(.fn_decode_rs3_inst(fn_decode_inst),
						 .fn_decode_rs3(x__h48));
  module_fn_decode_rs1 instance_fn_decode_rs1_7(.fn_decode_rs1_inst(fn_decode_inst),
						.fn_decode_rs1(x__h49));
  module_fn_decode_rs2 instance_fn_decode_rs2_8(.fn_decode_rs2_inst(fn_decode_inst),
						.fn_decode_rs2_csrs(fn_decode_csrs),
						.fn_decode_rs2(x__h50));
  module_fn_decode_rd instance_fn_decode_rd_9(.fn_decode_rd_inst(fn_decode_inst),
					      .fn_decode_rd(x__h103));
  module_fn_decode_trapcause instance_fn_decode_trapcause_11(.fn_decode_trapcause_inst(fn_decode_inst),
							     .fn_decode_trapcause_csrs(fn_decode_csrs),
							     .fn_decode_trapcause_debug(fn_decode_debug),
							     .fn_decode_trapcause(temp1___1__h197));
  module_fn_decode_insttype instance_fn_decode_insttype_5(.fn_decode_insttype_inst(fn_decode_inst),
							  .fn_decode_insttype_csrs(fn_decode_csrs),
							  .fn_decode_insttype_debug(fn_decode_debug),
							  .fn_decode_insttype(fn_decode_insttype___d12));
  module_fn_decode_mem_access instance_fn_decode_mem_access_4(.fn_decode_mem_access_inst(fn_decode_inst),
							      .fn_decode_mem_access(fn_decode_mem_access___d13));
  module_fn_decode_rdtype instance_fn_decode_rdtype_0(.fn_decode_rdtype_inst(fn_decode_inst),
						      .fn_decode_rdtype(fn_decode_rdtype___d8));
  module_fn_decode_rs1type instance_fn_decode_rs1type_2(.fn_decode_rs1type_inst(fn_decode_inst),
							.fn_decode_rs1type(fn_decode_rs1type___d9));
  module_fn_decode_rs2type instance_fn_decode_rs2type_3(.fn_decode_rs2type_inst(fn_decode_inst),
							.fn_decode_rs2type_compressed(fn_decode_compressed),
							.fn_decode_rs2type(fn_decode_rs2type___d10));
  module_fn_decode_rs3type instance_fn_decode_rs3type_1(.fn_decode_rs3type_inst(fn_decode_inst),
							.fn_decode_rs3type(fn_decode_rs3type___d7));
  assign instr_meta_funct_cause__h120 =
	     (fn_decode_insttype___d12 == 4'd6) ?
	       temp1___1__h197 :
	       temp1__h38 ;
  assign temp1__h38 =
	     { fn__h36,
	       (fn_decode_insttype___d12 == 4'd8 &&
		fn_decode_inst[14:12] == 3'b111) ?
		 fn_decode_csrs[192:190] :
		 fn_decode_inst[14:12] } ;
endmodule  // module_fn_decode

