//
// Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
//
// On Tue Jul 29 14:28:07 +04 2025
//
//
// Ports:
// Name                         I/O  size props
// fn_decode_trapcause            O     7
// fn_decode_trapcause_inst       I    32
// fn_decode_trapcause_csrs       I   242
// fn_decode_trapcause_debug      I     5
//
// Combinational paths from inputs to outputs:
//   (fn_decode_trapcause_inst,
//    fn_decode_trapcause_csrs,
//    fn_decode_trapcause_debug) -> fn_decode_trapcause
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_decode_trapcause(fn_decode_trapcause_inst,
				  fn_decode_trapcause_csrs,
				  fn_decode_trapcause_debug,
				  fn_decode_trapcause);
  // value method fn_decode_trapcause
  input  [31 : 0] fn_decode_trapcause_inst;
  input  [241 : 0] fn_decode_trapcause_csrs;
  input  [4 : 0] fn_decode_trapcause_debug;
  output [6 : 0] fn_decode_trapcause;

  // signals for module outputs
  reg [6 : 0] fn_decode_trapcause;

  // value method fn_decode_trapcause
  always@(fn_decode_trapcause_inst or
	  fn_decode_trapcause_csrs or fn_decode_trapcause_debug)
  begin
    case (fn_decode_trapcause_inst)
      32'b00000000000000000000000001110011:
	  fn_decode_trapcause =
	      (fn_decode_trapcause_csrs[148] &&
	       fn_decode_trapcause_csrs[189:188] == 2'd0) ?
		7'd8 :
		((fn_decode_trapcause_csrs[146] &&
		  fn_decode_trapcause_csrs[189:188] == 2'd1) ?
		   7'd9 :
		   7'd11);
      32'b00000000000100000000000001110011:
	  fn_decode_trapcause =
	      (fn_decode_trapcause_csrs[208] &&
	       !fn_decode_trapcause_debug[3] &&
	       fn_decode_trapcause_csrs[189:188] == 2'd3 ||
	       fn_decode_trapcause_csrs[206] &&
	       !fn_decode_trapcause_debug[3] &&
	       fn_decode_trapcause_csrs[189:188] == 2'd1 ||
	       fn_decode_trapcause_csrs[205] &&
	       !fn_decode_trapcause_debug[3] &&
	       fn_decode_trapcause_csrs[189:188] == 2'd0) ?
		7'd25 :
		7'd3;
      default: fn_decode_trapcause = 7'd2;
    endcase
  end
endmodule  // module_fn_decode_trapcause

