//
// Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
//
// On Tue Jul 29 14:28:05 +04 2025
//
//
// Ports:
// Name                         I/O  size props
// fn_bru2                        O     1
// fn_bru2_op1                    I    64
// fn_bru2_op2                    I    64
// fn_bru2_fn                     I     4
//
// Combinational paths from inputs to outputs:
//   (fn_bru2_op1, fn_bru2_op2, fn_bru2_fn) -> fn_bru2
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_bru2(fn_bru2_op1,
		      fn_bru2_op2,
		      fn_bru2_fn,
		      fn_bru2);
  // value method fn_bru2
  input  [63 : 0] fn_bru2_op1;
  input  [63 : 0] fn_bru2_op2;
  input  [3 : 0] fn_bru2_fn;
  output fn_bru2;

  // signals for module outputs
  wire fn_bru2;

  // remaining internal signals
  wire [63 : 0] inv__h19,
		inv_op2__h20,
		op1_xor_op2__h21,
		x01_PLUS_y02__q1,
		x__h201,
		y__h202;
  wire IF_fn_bru2_op1_BIT_63_EQ_fn_bru2_op2_BIT_63_TH_ETC___d14;

  // value method fn_bru2
  assign fn_bru2 =
	     fn_bru2_fn[0] ^
	     (fn_bru2_fn[3] ?
		IF_fn_bru2_op1_BIT_63_EQ_fn_bru2_op2_BIT_63_TH_ETC___d14 :
		op1_xor_op2__h21 == 64'd0) ;

  // remaining internal signals
  assign IF_fn_bru2_op1_BIT_63_EQ_fn_bru2_op2_BIT_63_TH_ETC___d14 =
	     (fn_bru2_op1[63] == fn_bru2_op2[63]) ?
	       x01_PLUS_y02__q1[63] :
	       (fn_bru2_fn[1] ? fn_bru2_op2[63] : fn_bru2_op1[63]) ;
  assign inv__h19 = {64{fn_bru2_fn[3]}} ;
  assign inv_op2__h20 = fn_bru2_op2 ^ inv__h19 ;
  assign op1_xor_op2__h21 = fn_bru2_op1 ^ inv_op2__h20 ;
  assign x01_PLUS_y02__q1 = x__h201 + y__h202 ;
  assign x__h201 = fn_bru2_op1 + inv_op2__h20 ;
  assign y__h202 = { 63'd0, fn_bru2_fn[3] } ;
endmodule  // module_fn_bru2

