//
// Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
//
// On Tue Jul 29 14:27:55 +04 2025
//
//
// Ports:
// Name                         I/O  size props
// fn_pmp_lookup                  O     8
// fn_pmp_lookup_req              I    34
// fn_pmp_lookup_priv             I     2
// fn_pmp_lookup_pmpcfg           I    32
// fn_pmp_lookup_pmpaddr          I   128
//
// Combinational paths from inputs to outputs:
//   (fn_pmp_lookup_req,
//    fn_pmp_lookup_priv,
//    fn_pmp_lookup_pmpcfg,
//    fn_pmp_lookup_pmpaddr) -> fn_pmp_lookup
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_pmp_lookup(fn_pmp_lookup_req,
			    fn_pmp_lookup_priv,
			    fn_pmp_lookup_pmpcfg,
			    fn_pmp_lookup_pmpaddr,
			    fn_pmp_lookup);
  // value method fn_pmp_lookup
  input  [33 : 0] fn_pmp_lookup_req;
  input  [1 : 0] fn_pmp_lookup_priv;
  input  [31 : 0] fn_pmp_lookup_pmpcfg;
  input  [127 : 0] fn_pmp_lookup_pmpaddr;
  output [7 : 0] fn_pmp_lookup;

  // signals for module outputs
  wire [7 : 0] fn_pmp_lookup;

  // remaining internal signals
  reg [6 : 0] x__h2152;
  wire [28 : 0] mask__h1138,
		mask__h1139,
		mask__h1358,
		mask__h1359,
		mask__h409,
		mask__h410,
		mask__h918,
		mask__h919,
		start_address__h1137,
		start_address__h1357,
		start_address__h408,
		start_address__h917,
		x__h1071,
		x__h1100,
		x__h1291,
		x__h1320,
		x__h1511,
		x__h1540,
		x__h851,
		x__h881,
		y__h1072,
		y__h1292,
		y__h1512,
		y__h852;
  wire IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d166,
       IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d168,
       NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d169,
       NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d46,
       NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d88,
       fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19,
       fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d41,
       fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d64,
       fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17,
       fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d39,
       fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d62,
       fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d99,
       x__h1094,
       x__h1314,
       x__h1534,
       x__h875;

  // value method fn_pmp_lookup
  assign fn_pmp_lookup =
	     { NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d169,
	       x__h2152 } ;

  // remaining internal signals
  assign IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d166 =
	     (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17 ||
	      !fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19 ||
	      fn_pmp_lookup_pmpcfg[4:3] == 2'd0) ?
	       (fn_pmp_lookup_pmpcfg[15] || fn_pmp_lookup_priv != 2'd3) &&
	       (fn_pmp_lookup_req[1:0] == 2'd0 && !fn_pmp_lookup_pmpcfg[8] ||
		fn_pmp_lookup_req[1:0] == 2'd1 && !fn_pmp_lookup_pmpcfg[9] ||
		fn_pmp_lookup_req[1:0] == 2'd2 && !fn_pmp_lookup_pmpcfg[10]) :
	       (fn_pmp_lookup_pmpcfg[7] || fn_pmp_lookup_priv != 2'd3) &&
	       (fn_pmp_lookup_req[1:0] == 2'd0 && !fn_pmp_lookup_pmpcfg[0] ||
		fn_pmp_lookup_req[1:0] == 2'd1 && !fn_pmp_lookup_pmpcfg[1] ||
		fn_pmp_lookup_req[1:0] == 2'd2 && !fn_pmp_lookup_pmpcfg[2]) ;
  assign IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d168 =
	     (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d99 &&
	      (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d62 ||
	       !fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d64 ||
	       fn_pmp_lookup_pmpcfg[20:19] == 2'd0)) ?
	       (fn_pmp_lookup_pmpcfg[31] || fn_pmp_lookup_priv != 2'd3) &&
	       (fn_pmp_lookup_req[1:0] == 2'd0 && !fn_pmp_lookup_pmpcfg[24] ||
		fn_pmp_lookup_req[1:0] == 2'd1 && !fn_pmp_lookup_pmpcfg[25] ||
		fn_pmp_lookup_req[1:0] == 2'd2 && !fn_pmp_lookup_pmpcfg[26]) :
	       (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d99 ?
		  (fn_pmp_lookup_pmpcfg[23] || fn_pmp_lookup_priv != 2'd3) &&
		  (fn_pmp_lookup_req[1:0] == 2'd0 &&
		   !fn_pmp_lookup_pmpcfg[16] ||
		   fn_pmp_lookup_req[1:0] == 2'd1 &&
		   !fn_pmp_lookup_pmpcfg[17] ||
		   fn_pmp_lookup_req[1:0] == 2'd2 &&
		   !fn_pmp_lookup_pmpcfg[18]) :
		  IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d166) ;
  assign NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d169 =
	     (NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d46 ||
	      !fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d62 &&
	      fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d64 &&
	      fn_pmp_lookup_pmpcfg[20:19] != 2'd0 ||
	      NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d88 &&
	      fn_pmp_lookup_pmpcfg[28:27] != 2'd0) &&
	     IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d168 ;
  assign NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d46 =
	     !fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17 &&
	     fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19 &&
	     fn_pmp_lookup_pmpcfg[4:3] != 2'd0 ||
	     !fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d39 &&
	     fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d41 &&
	     fn_pmp_lookup_pmpcfg[12:11] != 2'd0 ;
  assign NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d88 =
	     fn_pmp_lookup_req[33:5] >=
	     (start_address__h1357 & mask__h1359) &&
	     fn_pmp_lookup_req[33:5] <= fn_pmp_lookup_pmpaddr[127:99] ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19 =
	     fn_pmp_lookup_req[33:5] <= fn_pmp_lookup_pmpaddr[31:3] ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d41 =
	     fn_pmp_lookup_req[33:5] <= fn_pmp_lookup_pmpaddr[63:35] ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d64 =
	     fn_pmp_lookup_req[33:5] <= fn_pmp_lookup_pmpaddr[95:67] ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17 =
	     fn_pmp_lookup_req[33:5] < (start_address__h408 & mask__h410) ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d39 =
	     fn_pmp_lookup_req[33:5] < (start_address__h917 & mask__h919) ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d62 =
	     fn_pmp_lookup_req[33:5] < (start_address__h1137 & mask__h1139) ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d99 =
	     (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17 ||
	      !fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19 ||
	      fn_pmp_lookup_pmpcfg[4:3] == 2'd0) &&
	     (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d39 ||
	      !fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d41 ||
	      fn_pmp_lookup_pmpcfg[12:11] == 2'd0) ;
  assign mask__h1138 = { fn_pmp_lookup_pmpaddr[94:67], x__h1314 } ;
  assign mask__h1139 =
	     (fn_pmp_lookup_pmpcfg[20:19] == 2'd3) ?
	       ~x__h1291 :
	       29'd536870911 ;
  assign mask__h1358 = { fn_pmp_lookup_pmpaddr[126:99], x__h1534 } ;
  assign mask__h1359 =
	     (fn_pmp_lookup_pmpcfg[28:27] == 2'd3) ?
	       ~x__h1511 :
	       29'd536870911 ;
  assign mask__h409 = { fn_pmp_lookup_pmpaddr[30:3], x__h875 } ;
  assign mask__h410 =
	     (fn_pmp_lookup_pmpcfg[4:3] == 2'd3) ? ~x__h851 : 29'd536870911 ;
  assign mask__h918 = { fn_pmp_lookup_pmpaddr[62:35], x__h1094 } ;
  assign mask__h919 =
	     (fn_pmp_lookup_pmpcfg[12:11] == 2'd3) ?
	       ~x__h1071 :
	       29'd536870911 ;
  assign start_address__h1137 =
	     (fn_pmp_lookup_pmpcfg[20:19] == 2'd1) ?
	       fn_pmp_lookup_pmpaddr[63:35] :
	       fn_pmp_lookup_pmpaddr[95:67] ;
  assign start_address__h1357 =
	     (fn_pmp_lookup_pmpcfg[28:27] == 2'd1) ?
	       fn_pmp_lookup_pmpaddr[95:67] :
	       fn_pmp_lookup_pmpaddr[127:99] ;
  assign start_address__h408 =
	     (fn_pmp_lookup_pmpcfg[4:3] == 2'd1) ?
	       29'd0 :
	       fn_pmp_lookup_pmpaddr[31:3] ;
  assign start_address__h917 =
	     (fn_pmp_lookup_pmpcfg[12:11] == 2'd1) ?
	       fn_pmp_lookup_pmpaddr[31:3] :
	       fn_pmp_lookup_pmpaddr[63:35] ;
  assign x__h1071 = mask__h918 & y__h1072 ;
  assign x__h1094 = ~(fn_pmp_lookup_pmpcfg[12:11] == 2'd2) ;
  assign x__h1100 = mask__h918 + 29'd1 ;
  assign x__h1291 = mask__h1138 & y__h1292 ;
  assign x__h1314 = ~(fn_pmp_lookup_pmpcfg[20:19] == 2'd2) ;
  assign x__h1320 = mask__h1138 + 29'd1 ;
  assign x__h1511 = mask__h1358 & y__h1512 ;
  assign x__h1534 = ~(fn_pmp_lookup_pmpcfg[28:27] == 2'd2) ;
  assign x__h1540 = mask__h1358 + 29'd1 ;
  assign x__h851 = mask__h409 & y__h852 ;
  assign x__h875 = ~(fn_pmp_lookup_pmpcfg[4:3] == 2'd2) ;
  assign x__h881 = mask__h409 + 29'd1 ;
  assign y__h1072 = ~x__h1100 ;
  assign y__h1292 = ~x__h1320 ;
  assign y__h1512 = ~x__h1540 ;
  assign y__h852 = ~x__h881 ;
  always@(fn_pmp_lookup_req)
  begin
    case (fn_pmp_lookup_req[1:0])
      2'd0: x__h2152 = 7'd5;
      2'd1: x__h2152 = 7'd7;
      default: x__h2152 = 7'd1;
    endcase
  end
endmodule  // module_fn_pmp_lookup

